### ISSUE TITLE
Release of 0.3.0

### ISSUE THREAD

**Issue by sgeisler** [bbqsrc/core2#4]
Hi, is there anything in particular preventing a v0.3.0 from being released? Using an alpha seems weird and is a bit unergonomic (tooling defaults to 0.0.0 as most recent release instead).

**Comment by bbqsrc** [comment]
I'm not receiving notifications for this repository for some reason. Super strange.

Will cut a v0.3.0 today.

**Comment by bbqsrc** [comment]
And done. 😄

**Comment by sgeisler** [comment]
Awesome, thank you!
