### ISSUE TITLE
core2 for fatfs on RISC-V

### ISSUE THREAD

**Issue by jeancf** [bbqsrc/core2#5]
Hi there. I am coming here from the bare-io entry on crates.io. I am writing a driver for the SD Card on the [Sipeed Longan Nano](https://longan.sipeed.com/en/) RISC-V micro-controller (no-std context). I am trying to provide an implementation of Read, Write and Seek that the [FAT FS](https://github.com/rafalh/rust-fatfs) can use to interface with an SD Card.

I guess I am checking in to check if this crate is actively maintained and if you see any issue with what I am trying to do.

Thanks

**Comment by bbqsrc** [comment]
Sounds fine. I would say that it's more passively maintained than actively.
